spring:
  profiles:
    active: dev

logging:
  level:
    root: info             # 전체 로그 레벨
    org.hibernate.SQL: debug          # SQL 로그 레벨을 디버그로 설정
    org.hibernate.type.descriptor.sql.BasicBinder: trace   # SQL 쿼리 파라미터 값 출력
