spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/testdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: cagim30
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: create-drop

mybatis:
  mapper-locations: classpath:mybatis/mapper/mariadb/**/**.xml
  # type-handlers-package: com.oh.demo.mapper.typehandler
  type-aliases-package: com.oh.demo.model
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100
