spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/testdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: cagim30
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop